// components/Dashboard/BottomNavBar.vue
<template>
  <view class="bottom-nav-bar">
    <view 
      v-for="item in navItems" 
      :key="item.id"
      class="nav-item"
      @click="$emit('tabChange', item.id)"
    >
      <uni-icons 
        :type="item.icon" 
        size="24" 
        :color="activeTab === item.id ? '#6C8EA4' : '#999999'"
      ></uni-icons>
      <text 
        class="label"
        :class="{ active: activeTab === item.id }"
      >{{ item.label }}</text>
    </view>
  </view>
</template>

<script>
export default {
  props: {
    activeTab: String
  },
  emits: ['tabChange'],
  data() {
    return {
      navItems: [
        { id: 'home', label: '首页', icon: 'home' },
        { id: 'yarn', label: '毛线库', icon: 'shop' },
        { id: 'discover', label: '发现', icon: 'navigate' },
        { id: 'profile', label: '我的', icon: 'person' }
      ]
    }
  }
}
</script>

<style lang="scss" scoped>
.bottom-nav-bar {
  height: 80px;
  border-top: 1px solid #E0E0E0;
  background-color: #ffffff;
  display: flex;
  align-items: center;
  justify-content: space-around;
  padding-bottom: 20px;
  
  .nav-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 4px;
    padding: 8px;

    .label {
      font-size: 10px;
      color: #999999;
      
      &.active {
        color: #6C8EA4;
      }
    }
  }
}
</style>

// Single Page Project Dashboard (1)/src/app/components/BottomNavBar.tsx
import { Home, Package, Compass, UserCircle } from "lucide-react";

interface BottomNavBarProps {
  activeTab: string;
  onTabChange: (tab: string) => void;
}

export function BottomNavBar({ activeTab, onTabChange }: BottomNavBarProps) {
  const navItems = [
    { id: "home", label: "首页", icon: Home },
    { id: "yarn", label: "毛线库", icon: Package },
    { id: "discover", label: "发现", icon: Compass },
    { id: "profile", label: "我的", icon: UserCircle },
  ];

  return (
    <div className="h-20 border-t border-[#E0E0E0] bg-white flex items-center justify-around px-4">
      {navItems.map((item) => {
        const Icon = item.icon;
        const isActive = activeTab === item.id;
        return (
          <button
            key={item.id}
            onClick={() => onTabChange(item.id)}
            className="flex flex-col items-center gap-1 transition-colors"
          >
            <Icon
              className={`w-6 h-6 ${
                isActive ? "text-[#6C8EA4]" : "text-[#999999]"
              }`}
            />
            <span
              className={`text-xs ${
                isActive ? "text-[#6C8EA4]" : "text-[#999999]"
              }`}
            >
              {item.label}
            </span>
          </button>
        );
      })}
    </div>
  );
}
