// components/Dashboard/ProjectCard.vue
<template>
  <view class="project-card" @click="$emit('click')" @longpress="$emit('longpress')">
    <image :src="imageUrl" mode="aspectFill" class="project-image" />
    <view class="project-info">
      <view class="header">
        <text class="title">{{ title }}</text>
        <text class="time">{{ lastUpdate }}</text>
      </view>
      <text class="description">{{ description }}</text>
      
      <view class="progress-section">
        <view class="progress-bar-bg">
          <view class="progress-bar-fill" :style="{ width: progress + '%' }"></view>
        </view>
        <text class="progress-text">{{ progress }}%</text>
      </view>

      <view class="yarn-colors">
        <view 
          v-for="(color, index) in yarnColors" 
          :key="index"
          class="color-dot"
          :style="{ backgroundColor: color }"
        ></view>
      </view>
    </view>
  </view>
</template>

<script>
export default {
  mounted() {
    // console.log('ProjectCard mounted:', this.title, 'Colors:', this.yarnColors);
  },
  props: {
    title: String,
    description: String,
    progress: Number,
    imageUrl: String,
    lastUpdate: String,
    yarnColors: Array
  }
}
</script>

<style lang="scss" scoped>
.project-card {
  background-color: #ffffff;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
  display: flex;
  margin-bottom: 16px;

  .project-image {
    width: 100px;
    height: 100px;
    flex-shrink: 0;
  }

  .project-info {
    flex: 1;
    padding: 12px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 4px;

      .title {
        font-size: 16px;
        font-weight: 600;
        color: #3A3A3A;
      }

      .time {
        font-size: 12px;
        color: #999999;
      }
    }

    .description {
      font-size: 12px;
      color: #666666;
      margin-bottom: 8px;
      display: -webkit-box;
      -webkit-box-orient: vertical;
      -webkit-line-clamp: 1;
      line-clamp: 1;
      overflow: hidden;
    }

    .progress-section {
      display: flex;
      align-items: center;
      gap: 8px;
      margin-bottom: 8px;

      .progress-bar-bg {
        flex: 1;
        height: 6px;
        background-color: #F0F0F0;
        border-radius: 3px;
        overflow: hidden;

        .progress-bar-fill {
          height: 100%;
          background-color: #6C8EA4;
          border-radius: 3px;
        }
      }

      .progress-text {
        font-size: 12px;
        color: #6C8EA4;
        font-weight: 500;
      }
    }

    .yarn-colors {
      display: flex;
      flex-wrap: wrap;
      gap: 4px;

      .color-dot {
        width: 12px;
        height: 12px;
        border-radius: 50%;
        border: 1px solid rgba(0,0,0,0.1);
      }
    }
  }
}
</style>

// Single Page Project Dashboard (1)/src/app/components/ProjectCard.tsx
import { Clock } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";

interface ProjectCardProps {
  id: string;
  title: string;
  description: string;
  progress: number;
  imageUrl: string;
  lastUpdate: string;
  yarnColors: string[];
  onClick?: () => void;
}

export function ProjectCard({
  title,
  description,
  progress,
  imageUrl,
  lastUpdate,
  yarnColors,
  onClick,
}: ProjectCardProps) {
  return (
    <div
      onClick={onClick}
      className="bg-white rounded-lg shadow-[0_2px_8px_rgba(0,0,0,0.05)] overflow-hidden hover:shadow-[0_4px_12px_rgba(0,0,0,0.1)] transition-shadow cursor-pointer"
    >
      <div className="relative h-48 overflow-hidden">
        <ImageWithFallback
          src={imageUrl}
          alt={title}
          className="w-full h-full object-cover"
        />
      </div>
      <div className="p-4">
        <h3 className="text-[#3A3A3A] mb-2">{title}</h3>
        <p className="text-sm text-[#666666] mb-3 line-clamp-2">
          {description}
        </p>
        
        <div className="flex items-center gap-2 mb-3">
          {yarnColors.map((color, index) => (
            <div
              key={index}
              className="w-6 h-6 rounded-full border border-[#E0E0E0]"
              style={{ backgroundColor: color }}
            />
          ))}
        </div>

        <div className="mb-3">
          <div className="flex items-center justify-between mb-1">
            <span className="text-sm text-[#666666]">进度</span>
            <span className="text-[#6C8EA4]">{progress}%</span>
          </div>
          <div className="h-2 bg-[#FAF9F6] rounded-full overflow-hidden">
            <div
              className="h-full bg-[#5BB98A] rounded-full transition-all"
              style={{ width: `${progress}%` }}
            />
          </div>
        </div>

        <div className="flex items-center text-xs text-[#999999]">
          <Clock className="w-3 h-3 mr-1" />
          {lastUpdate}
        </div>
      </div>
    </div>
  );
}
